
export const AUTH_SIGN_IN_REQUEST_SIGNAL = "AUTH_SIGN_IN_REQUEST_SIGNAL";
export const AUTH_SIGN_IN_SUCCESS_SIGNAL = "AUTH_SIGN_IN_SUCCESS_SIGNAL";
export const AUTH_SIGN_IN_FAILURE_SIGNAL = "AUTH_SIGN_IN_FAILURE_SIGNAL";
export const AUTH_SIGN_UP_REQUEST_SIGNAL = "AUTH_SIGN_OUT_REQUEST_SIGNAL";
export const AUTH_SIGN_UP_SUCCESS_SIGNAL = "AUTH_SIGN_OUT_SUCCESS_SIGNAL";
export const AUTH_SIGN_UP_FAILURE_SIGNAL = "AUTH_SIGN_OUT_FAILURE_SIGNAL";
export const AUTH_SIGN_OUT_SIGNAL = "AUTH_SIGN_OUT_SIGNAL";

export const AUTH_REDIRECT_URL_SIGNAL = "AUTH_REDIRECT_URL_SIGNAL";
