
export const COMMON_LIST_ACTION = "COMMON_LIST_ACTION";
export const COMMON_ADD_ACTION = "COMMON_ADD_ACTION";
export const COMMON_EDIT_ACTION = "COMMON_EDIT_ACTION";
export const COMMON_DELETE_ACTION = "COMMON_DELETE_ACTION";

export const COMMON_REQUEST_SIGNAL = "COMMON_REQUEST_SIGNAL";
export const COMMON_SUCCESS_SIGNAL = "COMMON_SUCCESS_SIGNAL";
export const COMMON_FAILURE_SIGNAL = "COMMON_FAILURE_SIGNAL";