
export const POST_A_JOB = {
  RESET_ALL: "MY_JOBS_POST_A_JOB_RESET_ALL",
  SET_IS_ACTIVE: "MY_JOBS_POST_A_JOB_SET_IS_ACTIVE",
  SET_STEP: "MY_JOBS_POST_A_JOB_SET_STEP",
  SET_JOB_INFORMATION: "MY_JOBS_POST_A_JOB_SET_JOB_INFORMATION",
  SET_CANDIDATE_REQUIREMENTS: "MY_JOBS_POST_A_JOB_SET_CANDIDATE_REQUIREMENTS",
  SET_SPECIALTIES: "MY_JOBS_POST_A_JOB_SET_SPECIALTIES",
  SET_QUESTIONNAIRE: "MY_JOBS_POST_A_JOB_SET_QUESTIONNAIRE",
};